[package]
name = "RSock"
version = "0.1.0"
authors = ["Exo-poulpe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
pnet = "0.25.0"