[package]
name = "RSock"
version = "0.1.0"
authors = ["Exo-poulpe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0

[dependencies]
clap = "2.33.3"
RSocklib = {path = "./RSocklib" }